# Deploy Content to Sentinel

variables:
  - name: VarResourceGroupName
    value: RG-
  - name: ConnectionName
    value: Sentinel-
  - name: VarWorkSpaceName
    value: LA-
  - name: VarWorkSpaceId
    value: $(WORKSPACEID)
  - name: VarTenantID
    value: $(TENANTID)
  - name: VarSubscriptionID
    value: $(SUBSCRIPTIONID)
 
trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Watchlists
  jobs:
  - job: Watchlists
    steps:
    - task: AzurePowerShell@5
      displayName: Watchlists
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'Watchlist'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'Watchlist'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: HuntingQueries_Parsers
  jobs:
  - job: HuntingQueries_Parsers
    steps:
    - task: AzurePowerShell@5
      displayName: HuntingQueries_Parsers
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'HuntingQuery,Parser'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'HuntingQuery,Parser'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: AnalyticsRules
  jobs:
  - job: AnalyticsRules
    steps:
    - task: AzurePowerShell@5
      displayName: AnalyticsRules
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'AnalyticsRule'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'AnalyticsRule'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: Workbooks
  jobs:
  - job: Workbooks
    steps:
    - task: AzurePowerShell@5
      displayName: Workbooks
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'Workbook'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'Workbook'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: Playbooks
  jobs:
  - job: Playbooks
    steps:
    - task: AzurePowerShell@5
      displayName: Playbooks
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'Playbook'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'Playbook'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: AutomationRules
  jobs:
  - job: AutomationRules
    steps:
    - task: AzurePowerShell@5
      displayName: AutomationRules
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'AutomationRule'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'AutomationRule'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
- stage: DataCollectionRules
  jobs:
  - job: DataCollectionRules
    steps:
    - task: AzurePowerShell@5
      displayName: DataCollectionRules
      inputs:
        azureSubscription: '$(ConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '.devops-pipeline/azure-sentinel-deploy.ps1'
        ScriptArguments: 
          -ResourceGroupName '$(VarResourceGroupName)'
          -ContentTypes 'DataCollectionRule'
          -WorkSpaceName '$(VarWorkSpaceName)'
          -WorkSpaceId '$(VarWorkSpaceId)'
          -systemAccessToken '$(System.AccessToken)'
          -branchName '$(Build.SourceBranchName)'
          -repositoryName '$(Build.Repository.Name)'
          -collectionUri '$(System.CollectionUri)'
          -projectId '$(System.TeamProject)'
          -sourceControlId 'DataCollectionRule'
          -rootDirectory '$(Build.SourcesDirectory)'
          -smartDeployment 'true'
          -TenantID '$(VarTenantID)'
          -SubscriptionID '$(VarSubscriptionID)'
        azurePowerShellVersion: 'LatestVersion'
